/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin_form;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class form_ad_main extends javax.swing.JFrame {

    /**
     * Creates new form form_ad_main
     */
    public form_ad_main() {
        initComponents();
    }

    private void Opened_Background(JLabel lab) {
        lab.setOpaque(true);
        lab.setBackground(Color.LIGHT_GRAY);
    }

    private void Closed_Background(JLabel lab) {
        lab.setBackground(null);
        lab.setOpaque(false);
    }

    private void Opened_JPanel_Form(JPanel form) {
        this.jPanel_HienThi.removeAll();
        this.jPanel_HienThi.setLayout(new BorderLayout());
        this.jPanel_HienThi.add(form, BorderLayout.CENTER);
        this.jPanel_HienThi.validate();
        this.jPanel_HienThi.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ChucNang = new javax.swing.JPanel();
        lb_khoa = new javax.swing.JLabel();
        lb_nganh = new javax.swing.JLabel();
        lb_lop = new javax.swing.JLabel();
        lb_hocphan = new javax.swing.JLabel();
        lb_lophocphan = new javax.swing.JLabel();
        lb_sinhvien = new javax.swing.JLabel();
        lb_thongke = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_HienThi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_ChucNang.setBackground(new java.awt.Color(102, 204, 255));

        lb_khoa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_khoa.setForeground(new java.awt.Color(51, 51, 51));
        lb_khoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\khoa.png")); // NOI18N
        lb_khoa.setText("Khoa");
        lb_khoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_khoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_khoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_khoaMouseExited(evt);
            }
        });

        lb_nganh.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_nganh.setForeground(new java.awt.Color(51, 51, 51));
        lb_nganh.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\nganh.png")); // NOI18N
        lb_nganh.setText("Ngành");
        lb_nganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nganhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_nganhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_nganhMouseExited(evt);
            }
        });

        lb_lop.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_lop.setForeground(new java.awt.Color(51, 51, 51));
        lb_lop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\lop.png")); // NOI18N
        lb_lop.setText("Lớp");
        lb_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_lopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_lopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_lopMouseExited(evt);
            }
        });

        lb_hocphan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_hocphan.setForeground(new java.awt.Color(51, 51, 51));
        lb_hocphan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\hocphan.png")); // NOI18N
        lb_hocphan.setText("Học phần");
        lb_hocphan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hocphanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_hocphanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_hocphanMouseExited(evt);
            }
        });

        lb_lophocphan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_lophocphan.setForeground(new java.awt.Color(51, 51, 51));
        lb_lophocphan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\lophocphan.png")); // NOI18N
        lb_lophocphan.setText("Lớp học phần");
        lb_lophocphan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_lophocphanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_lophocphanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_lophocphanMouseExited(evt);
            }
        });

        lb_sinhvien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_sinhvien.setForeground(new java.awt.Color(51, 51, 51));
        lb_sinhvien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\sinhvien.png")); // NOI18N
        lb_sinhvien.setText("Sinh viên");
        lb_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_sinhvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_sinhvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_sinhvienMouseExited(evt);
            }
        });

        lb_thongke.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_thongke.setForeground(new java.awt.Color(51, 51, 51));
        lb_thongke.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\thongke.png")); // NOI18N
        lb_thongke.setText("Thống kê");
        lb_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_thongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_thongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_thongkeMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-earth-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_ChucNangLayout = new javax.swing.GroupLayout(jPanel_ChucNang);
        jPanel_ChucNang.setLayout(jPanel_ChucNangLayout);
        jPanel_ChucNangLayout.setHorizontalGroup(
            jPanel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_khoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_nganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_lop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_hocphan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_lophocphan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(lb_sinhvien, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(lb_thongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ChucNangLayout.setVerticalGroup(
            jPanel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lb_khoa)
                .addGap(18, 18, 18)
                .addComponent(lb_nganh)
                .addGap(18, 18, 18)
                .addComponent(lb_lop)
                .addGap(18, 18, 18)
                .addComponent(lb_hocphan)
                .addGap(18, 18, 18)
                .addComponent(lb_lophocphan)
                .addGap(26, 26, 26)
                .addComponent(lb_sinhvien)
                .addGap(18, 18, 18)
                .addComponent(lb_thongke)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel_HienThiLayout = new javax.swing.GroupLayout(jPanel_HienThi);
        jPanel_HienThi.setLayout(jPanel_HienThiLayout);
        jPanel_HienThiLayout.setHorizontalGroup(
            jPanel_HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        jPanel_HienThiLayout.setVerticalGroup(
            jPanel_HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_HienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_HienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_khoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khoaMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lb_khoa);
    }//GEN-LAST:event_lb_khoaMouseEntered

    private void lb_khoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khoaMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lb_khoa);
    }//GEN-LAST:event_lb_khoaMouseExited

    private void lb_khoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khoaMouseClicked
        // TODO add your handling code here:
        form_ad_khoa_JPanel form = new form_ad_khoa_JPanel();
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lb_khoaMouseClicked

    private void lb_nganhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nganhMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lb_nganh);
    }//GEN-LAST:event_lb_nganhMouseEntered

    private void lb_nganhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nganhMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lb_nganh);
    }//GEN-LAST:event_lb_nganhMouseExited

    private void lb_nganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nganhMouseClicked
        // TODO add your handling code here:
        form_ad_nganh_JPanel form = new form_ad_nganh_JPanel();
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lb_nganhMouseClicked

    private void lb_lopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lopMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lb_lop);
    }//GEN-LAST:event_lb_lopMouseEntered

    private void lb_lopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lopMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lb_lop);
    }//GEN-LAST:event_lb_lopMouseExited

    private void lb_lopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lopMouseClicked
        // TODO add your handling code here:
        form_ad_lop_JPanel form = new form_ad_lop_JPanel();
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lb_lopMouseClicked

    private void lb_hocphanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hocphanMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lb_hocphan);
    }//GEN-LAST:event_lb_hocphanMouseEntered

    private void lb_hocphanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hocphanMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lb_hocphan);

    }//GEN-LAST:event_lb_hocphanMouseExited

    private void lb_hocphanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hocphanMouseClicked
        // TODO add your handling code here:
        form_ad_lophocphan_JPanel form = new form_ad_lophocphan_JPanel();
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lb_hocphanMouseClicked

    private void lb_lophocphanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lophocphanMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lb_lophocphan);

    }//GEN-LAST:event_lb_lophocphanMouseEntered

    private void lb_lophocphanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lophocphanMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lb_lophocphan);

    }//GEN-LAST:event_lb_lophocphanMouseExited

    private void lb_lophocphanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lophocphanMouseClicked
        // TODO add your handling code here:
        form_ad_lophocphan_JPanel form = new form_ad_lophocphan_JPanel();
        Opened_JPanel_Form(form);

    }//GEN-LAST:event_lb_lophocphanMouseClicked

    private void lb_sinhvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sinhvienMouseEntered
        // TODO add your handling code here:
              Opened_Background(this.lb_sinhvien);

    }//GEN-LAST:event_lb_sinhvienMouseEntered

    private void lb_sinhvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sinhvienMouseExited
        // TODO add your handling code here:
                Closed_Background(this.lb_sinhvien);

    }//GEN-LAST:event_lb_sinhvienMouseExited

    private void lb_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sinhvienMouseClicked
        // TODO add your handling code here:
        form_ad_sinhvien form = new form_ad_sinhvien();
        form.setVisible(true);
    }//GEN-LAST:event_lb_sinhvienMouseClicked

    private void lb_thongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_thongkeMouseEntered
        // TODO add your handling code here:
                Opened_Background(this.lb_thongke);

    }//GEN-LAST:event_lb_thongkeMouseEntered

    private void lb_thongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_thongkeMouseExited
        // TODO add your handling code here:
                Closed_Background(this.lb_thongke);

    }//GEN-LAST:event_lb_thongkeMouseExited

    private void lb_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_thongkeMouseClicked
        // TODO add your handling code here:
        form_ad_thongke_JPanel form = new form_ad_thongke_JPanel();
                Opened_JPanel_Form(form);

    }//GEN-LAST:event_lb_thongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_ad_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_ad_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_ad_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_ad_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_ad_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_ChucNang;
    private javax.swing.JPanel jPanel_HienThi;
    private javax.swing.JLabel lb_hocphan;
    private javax.swing.JLabel lb_khoa;
    private javax.swing.JLabel lb_lop;
    private javax.swing.JLabel lb_lophocphan;
    private javax.swing.JLabel lb_nganh;
    private javax.swing.JLabel lb_sinhvien;
    private javax.swing.JLabel lb_thongke;
    // End of variables declaration//GEN-END:variables
}
