/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin_form;

import data.KetNoi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class form_ad_sinhvien_JPanel extends javax.swing.JPanel {

    public String masv = null;

    /**
     * Creates new form form_ad_sinhvien_JPanel
     */
    public form_ad_sinhvien_JPanel() {
        initComponents();
        HienThi();
    }

    private String getMaLop(String TenLop) throws SQLException {
        Connection kn = KetNoi.KNCSDL();
        try {
            Statement stm = kn.createStatement();
            String sql_l = "SELECT MaLop "
                    + "FROM lop "
                    + "WHERE TenLop = '" + TenLop + "'";
            ResultSet rs = stm.executeQuery(sql_l);
            rs.next();
            return rs.getString(1);
        } catch (SQLException ex) {
            Logger.getLogger(form_ad_sinhvien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;  // Re-throw the SQLException for proper handling
        }
    }

    private void HienThi() {
        Connection kn;
        try {
            kn = KetNoi.KNCSDL();
            Statement stm = kn.createStatement();
            String sqlThem1 = "SELECT sv.MaSinhVien, sv.MatKhau, sv.TenSinhVien, sv.Email, sv.SoDienThoai, sv.DiaChi, sv.NgaySinh, sv.GioiTinh, sv.NgayVaoTruong, l.TenLop, n.TenNganh "
                    + "FROM sinhvien sv "
                    + "JOIN lop l ON sv.MaLop = l.MaLop "
                    + "JOIN nganh n ON l.MaNganh = n.MaNganh "
                    + "WHERE sv.MaSinhVien NOT LIKE 'ADMIN'";
            ResultSet rs = stm.executeQuery(sqlThem1);
            DefaultTableModel dtm = (DefaultTableModel) tb_sinhvien.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                Object objliss[] = {
                    rs.getString("MatKhau"),
                    rs.getString("MaSinhVien"),
                    rs.getString("TenSinhVien"),
                    rs.getString("TenLop"),
                    rs.getString("TenNganh"),
                    rs.getString("Email"),
                    rs.getString("SoDienThoai"),
                    rs.getString("DiaChi"),
                    rs.getString("NgaySinh"),
                    rs.getString("GioiTinh"),
                    rs.getString("NgayVaoTruong")
                };
                dtm.addRow(objliss);
                tb_sinhvien.setModel(dtm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(form_ad_sinhvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTSV = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sinhvien = new javax.swing.JTable();
        txtDC = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNVT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbbTL = new javax.swing.JComboBox<>();
        txtTKT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combTN = new javax.swing.JComboBox<>();
        btreset = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        txtGT = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtMK = new javax.swing.JTextField();

        jLabel5.setText("Tìm kiếm theo:");

        jLabel3.setText("Tên sinh viên:");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tb_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mật khẩu", " Mã SV", "Ten SV", "Tên lớp", "Tên ngành", "Email", "Số ĐT", "Địa chỉ", "Ngày sinh", "Giới tính", "Ngày vào trường"
            }
        ));
        tb_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sinhvien);

        jLabel10.setText("Ngày vào trường");

        jLabel7.setText("Địa chỉ:");

        jLabel1.setText("Tên lớp:");

        cbbTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DHTI1A1", "DHKD1A1", "DHTA1A1", "DHTI1A1" }));
        cbbTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTLActionPerformed(evt);
            }
        });

        jLabel11.setText("Tên ngành:");

        jLabel4.setText("Email:");

        combTN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nghệ Thông tin", "Quản trị Kinh doanh", "Cơ khí", "Tiếng Anh" }));

        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        jLabel8.setText("Ngày sinh:");

        jLabel6.setText("Số điện thoại:");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel9.setText("Giới tính:");

        jLabel2.setText("Mật khẩu:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(combTN, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(txtMK, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(txtTSV, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(cbbTL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(41, 41, 41)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGT, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNVT, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNS, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTKT, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(combTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(txtNVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbbTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtTKT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            // TODO add your handling code here:
            String query = "update sinhvien set "
                    + "MatKhau= '" + txtMK.getText() + "' "
                    + ", TenSinhVien = N'" + txtTSV.getText() + "' "
                    + ", MaLop= '" + getMaLop(cbbTL.getSelectedItem().toString()) + "'"
                    + ", Email = '" + txtEmail.getText() + "' , SoDienThoai = '" + txtSDT.getText() + "' "
                    + ", DiaChi = N'" + txtDC.getText() + "' "
                    + ", NgaySinh = '" + txtNS.getText() + "' "
                    + ", GioiTinh = '" + txtGT.getText() + "' "
                    + ", NgayVaoTruong = '" + txtNVT.getText() + "' where MaSinhVien = '" + masv + "'";
            Connection c = KetNoi.KNCSDL();
            Statement stm = c.createStatement();
            stm.executeUpdate(query);
            HienThi();
        } catch (SQLException ex) {
            Logger.getLogger(form_ad_sinhvien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tb_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sinhvienMouseClicked
        // TODO add your handling code here:
        int row = tb_sinhvien.getSelectedRow();
        // lấy giá trị của từng cột hàng đag chọn
        String MK = tb_sinhvien.getValueAt(row, 0).toString();
        String TenSV = tb_sinhvien.getValueAt(row, 2).toString();
        String TenN = tb_sinhvien.getValueAt(row, 4).toString();
        String TenL = tb_sinhvien.getValueAt(row, 3).toString();
        String Emai = tb_sinhvien.getValueAt(row, 5).toString();
        String SDT = tb_sinhvien.getValueAt(row, 6).toString();
        String DC = tb_sinhvien.getValueAt(row, 7).toString();
        String NS = tb_sinhvien.getValueAt(row, 8).toString();
        String GT = tb_sinhvien.getValueAt(row, 9).toString();
        String NVT = tb_sinhvien.getValueAt(row, 10).toString();
        masv = tb_sinhvien.getValueAt(row, 1).toString();
        //đưa dữ liệu vừa lấy dc lên các textview
        txtMK.setText(MK);
        txtTSV.setText(TenSV);
        combTN.setSelectedItem(TenN);
        cbbTL.setSelectedItem(TenL);
        txtEmail.setText(Emai);
        txtSDT.setText(SDT);
        txtDC.setText(SDT);
        txtNS.setText(NS);
        txtGT.setText(GT);
        txtNVT.setText(NVT);

    }//GEN-LAST:event_tb_sinhvienMouseClicked

    private void cbbTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTLActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        HienThi();
        txtMK.setText("");
        txtTSV.setText("");
        txtEmail.setText("");
        combTN.setSelectedItem("");
        cbbTL.setSelectedItem("");
        txtSDT.setText("");
        txtNS.setText("");
        txtGT.setText("");
        txtNVT.setText("");
        txtDC.setText("");
    }//GEN-LAST:event_btresetActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String query = "delete from sinhvien where TenSinhVien = '" + txtTSV.getText() + "'";
            Connection c = KetNoi.KNCSDL();
            Statement stm = c.createStatement();
            stm.executeUpdate(query);
            HienThi();
        } catch (SQLException ex) {
            Logger.getLogger(form_ad_sinhvien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        Connection kn;
        try {
            kn = KetNoi.KNCSDL();
            Statement stm = kn.createStatement();
            String sqlThem1 = "SELECT sv.MaSinhVien, sv.MatKhau, sv.TenSinhVien, sv.Email, sv.SoDienThoai, sv.DiaChi, sv.NgaySinh, sv.GioiTinh, sv.NgayVaoTruong, l.TenLop, n.TenNganh FROM sinhvien sv JOIN lop l ON sv.MaLop = l.MaLop JOIN nganh n ON l.MaNganh = n.MaNganh where sv.MaSinhVien = '" + txtTKT.getText() + "' or sv.TenSinhVien = '" + txtTKT.getText() + "'";
            ResultSet rs = stm.executeQuery(sqlThem1);
            DefaultTableModel dtm = (DefaultTableModel) tb_sinhvien.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                Object objliss[] = {
                    rs.getString("MatKhau"),
                    rs.getString("MaSinhVien"),
                    rs.getString("TenSinhVien"),
                    rs.getString("TenLop"),
                    rs.getString("TenNganh"),
                    rs.getString("Email"),
                    rs.getString("SoDienThoai"),
                    rs.getString("DiaChi"),
                    rs.getString("NgaySinh"),
                    rs.getString("GioiTinh"),
                    rs.getString("NgayVaoTruong")
                };
                dtm.addRow(objliss);
                tb_sinhvien.setModel(dtm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(form_ad_sinhvien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String combTN1 = combTN.getSelectedItem().toString();
        String combTL1 = cbbTL.getSelectedItem().toString();
        Connection kn;
        String A;
        int B;

        try {
            kn = KetNoi.KNCSDL();
            Statement stm = kn.createStatement();
            String sql_1 = "SELECT Count(*) FROM sinhvien";
            ResultSet rs = stm.executeQuery(sql_1);
            int MaSV = 0;
            if (rs.next()) {
                MaSV = rs.getInt(1) + 1;
            }

            String MaLHP = "";
            if (MaSV < 10) {
                MaLHP = "SV0" + MaSV;
            } else {
                MaLHP = "SV" + MaSV;
            }

            String sql = "insert into sinhvien(MaSinhVien, MatKhau, TenSinhVien, MaLop, Email, SoDienThoai, DiaChi, NgaySinh, GioiTinh, NgayVaoTruong)"
                    + " values ('" + MaLHP + "', '" + txtMK.getText() + "','" + txtTSV.getText() + "', '" + getMaLop(cbbTL.getSelectedItem().toString()) + "','" + txtEmail.getText() + "','" + txtSDT.getText() + "','" + txtDC.getText() + "','" + txtNS.getText() + "','" + txtGT.getText() + "','" + txtNVT.getText() + "')";
            stm.executeUpdate(sql);
            HienThi();
        } catch (SQLException ex) {
            Logger.getLogger(form_ad_sinhvien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LoadDataIntoComboBox() {

    }

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btreset;
    private javax.swing.JComboBox<String> cbbTL;
    private javax.swing.JComboBox<String> combTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_sinhvien;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGT;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtNS;
    private javax.swing.JTextField txtNVT;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTKT;
    private javax.swing.JTextField txtTSV;
    // End of variables declaration//GEN-END:variables
}
