/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sv_form;

import data.KetNoi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class form_sv_hienthiHocPhan_JPanel extends javax.swing.JPanel {

    private String maSinhVien;

    /**
     * Creates new form form_sv_hienthiHocPhan_JPanel
     */
    public form_sv_hienthiHocPhan_JPanel(String maSinhVien) {
        initComponents();
        this.maSinhVien = maSinhVien;

    }


    // Phương thức hiển thị dữ liệu lên bảng
    public void HienThi(String sql, String namkyhoc) {
        try {
            Connection cn = KetNoi.KNCSDL();
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, namkyhoc);
            ps.setString(2, this.maSinhVien);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) tbHTHocPhan.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                Object objliss[] = {
                    rs.getString("MaHocPhan"),
                    rs.getString("TenHocPhan"),
                    rs.getString("SoTinChi"),
                    rs.getString("HocPhi"),
                    rs.getString("SoDonViHocTrinh")
                };
                dtm.addRow(objliss);
            }
            tbHTHocPhan.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(form_sv_hienthiHocPhan_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combNamKyHoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHTHocPhan = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        combNamKyHoc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        combNamKyHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm 1 Kỳ 1", "Năm 1 Kỳ 2", "Năm 2 Kỳ 1", "Năm 2 Kỳ 2", "Năm 3 Kỳ 1", "Năm 3 Kỳ 2", "Năm 4 Kỳ 1", "Năm 4 Kỳ 2" }));

        tbHTHocPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ", "Học phí", "Số đơn vị học trình"
            }
        ));
        jScrollPane1.setViewportView(tbHTHocPhan);

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kỳ Học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(combNamKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combNamKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String namkyhoc = combNamKyHoc.getSelectedItem().toString();
        String sql = "SELECT * FROM hocphan WHERE NamKyHoc = ? AND MaHocPhan IN (SELECT hp.MaHocPhan "
                                                                                + "FROM hocphan AS hp "
                                                                                + "JOIN lophocphan AS lhp ON lhp.MaHocPhan = hp.MaHocPhan "
                                                                                + "JOIN dangkyhocphan AS dkhp ON dkhp.MaLopHocPhan = lhp.MaLopHocPhan AND dkhp.MaSinhVien = ?)";
        HienThi(sql, namkyhoc);
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> combNamKyHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHTHocPhan;
    // End of variables declaration//GEN-END:variables
}
