/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sv_form;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class form_sv_main extends javax.swing.JFrame {

    /**
     * Creates new form form_sv_main
     */
    String maSinhVien;

    public form_sv_main(String maSinhVien) {
        initComponents();
        this.maSinhVien = maSinhVien;

        form_sv_hienthiThongTin_JPanel form = new form_sv_hienthiThongTin_JPanel(this.maSinhVien);
        Opened_JPanel_Form(form);
    }

    private form_sv_main() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void Opened_Background(JLabel lab) {
        lab.setOpaque(true);
        lab.setBackground(Color.LIGHT_GRAY);
    }

    private void Closed_Background(JLabel lab) {
        lab.setBackground(null);
        lab.setOpaque(false);
    }

    private void Opened_JPanel_Form(JPanel form) {
        this.jPanel_HienThi.removeAll();
        this.jPanel_HienThi.setLayout(new BorderLayout());
        this.jPanel_HienThi.add(form, BorderLayout.CENTER);
        this.jPanel_HienThi.validate();
        this.jPanel_HienThi.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbKetQuaHocPhan = new javax.swing.JLabel();
        lb_hocphan = new javax.swing.JLabel();
        lbTrangChu = new javax.swing.JLabel();
        jPanel_HienThi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        lbKetQuaHocPhan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbKetQuaHocPhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKetQuaHocPhan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\KetQuaHocTap.png")); // NOI18N
        lbKetQuaHocPhan.setText("Kết quả học tập");
        lbKetQuaHocPhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbKetQuaHocPhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbKetQuaHocPhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbKetQuaHocPhanMouseExited(evt);
            }
        });

        lb_hocphan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_hocphan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hocphan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\sv_HocPhan.png")); // NOI18N
        lb_hocphan.setText("Học phần");
        lb_hocphan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hocphanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_hocphanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_hocphanMouseExited(evt);
            }
        });

        lbTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrangChu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Máy tính\\UNETI\\TH_LTM\\BTL\\Code\\GIT_BTL_QLSV\\BTL_THLTM\\BTL_QLSV\\src\\image\\TrangChu.png")); // NOI18N
        lbTrangChu.setText("Trang chủ");
        lbTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTrangChuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_hocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbKetQuaHocPhan)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(lbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKetQuaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(465, 465, 465))
        );

        javax.swing.GroupLayout jPanel_HienThiLayout = new javax.swing.GroupLayout(jPanel_HienThi);
        jPanel_HienThi.setLayout(jPanel_HienThiLayout);
        jPanel_HienThiLayout.setHorizontalGroup(
            jPanel_HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_HienThiLayout.setVerticalGroup(
            jPanel_HienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_HienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_HienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangChuMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lbTrangChu);
    }//GEN-LAST:event_lbTrangChuMouseEntered

    private void lbTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangChuMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lbTrangChu);
    }//GEN-LAST:event_lbTrangChuMouseExited

    private void lb_hocphanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hocphanMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lb_hocphan);
    }//GEN-LAST:event_lb_hocphanMouseEntered

    private void lb_hocphanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hocphanMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lb_hocphan);
    }//GEN-LAST:event_lb_hocphanMouseExited

    private void lbKetQuaHocPhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKetQuaHocPhanMouseEntered
        // TODO add your handling code here:
        Opened_Background(this.lbKetQuaHocPhan);
    }//GEN-LAST:event_lbKetQuaHocPhanMouseEntered

    private void lbKetQuaHocPhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKetQuaHocPhanMouseExited
        // TODO add your handling code here:
        Closed_Background(this.lbKetQuaHocPhan);
    }//GEN-LAST:event_lbKetQuaHocPhanMouseExited

    private void lbTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangChuMouseClicked
        // TODO add your handling code here:
        form_sv_hienthiThongTin_JPanel form = new form_sv_hienthiThongTin_JPanel(this.maSinhVien);
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lbTrangChuMouseClicked

    private void lb_hocphanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hocphanMouseClicked
        // TODO add your handling code here:
        form_sv_hienthiHocPhan_JPanel form = new form_sv_hienthiHocPhan_JPanel(this.maSinhVien);
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lb_hocphanMouseClicked

    private void lbKetQuaHocPhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKetQuaHocPhanMouseClicked
        // TODO add your handling code here:
        form_sv_hienthiDiem_JPanel form = new form_sv_hienthiDiem_JPanel(this.maSinhVien);
        Opened_JPanel_Form(form);
    }//GEN-LAST:event_lbKetQuaHocPhanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_sv_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_sv_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_sv_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_sv_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_sv_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_HienThi;
    private javax.swing.JLabel lbKetQuaHocPhan;
    private javax.swing.JLabel lbTrangChu;
    private javax.swing.JLabel lb_hocphan;
    // End of variables declaration//GEN-END:variables
}
